-------------------- spdw_modifica_precio_producto ---------------------------------
ALTER PROCEDURE [dbo].[spdw_modifica_precio_producto](@ve_operacion			VARCHAR(20))

AS
BEGIN
	DELETE FROM DETALLE_PRODUCTO_CAMBIO

	DECLARE	@vl_cod_log_cambio numeric(10)

	IF(@ve_operacion='VISTA_PREVIA')BEGIN

		SELECT @vl_cod_log_cambio = CONVERT(NUMERIC, VALOR) 
		FROM PARAMETRO
		WHERE COD_PARAMETRO = '84'

		INSERT INTO DETALLE_PRODUCTO_CAMBIO
		SELECT LC.COD_LOG_CAMBIO
			 ,FECHA_CAMBIO
			 ,NOM_USUARIO
			 ,KEY_TABLA
			 ,VALOR_ANTIGUO
			 ,VALOR_NUEVO
			 ,'COMERCIAL'
		FROM LOG_CAMBIO LC
			,DETALLE_CAMBIO DC
			,USUARIO U
		WHERE LC.COD_LOG_CAMBIO > @vl_cod_log_cambio
		AND LC.COD_LOG_CAMBIO = DC.COD_LOG_CAMBIO
		AND U.COD_USUARIO = LC.COD_USUARIO
		AND NOM_TABLA = 'PRODUCTO'
		AND NOM_CAMPO = 'PRECIO_VENTA_INTERNO'

		SELECT @vl_cod_log_cambio = CONVERT(NUMERIC, VALOR) 
		FROM PARAMETRO
		WHERE COD_PARAMETRO = '85'

		INSERT INTO DETALLE_PRODUCTO_CAMBIO
		SELECT LC.COD_LOG_CAMBIO
			 ,FECHA_CAMBIO
			 ,NOM_USUARIO
			 ,KEY_TABLA
			 ,VALOR_ANTIGUO
			 ,VALOR_NUEVO
			 ,'BODEGA'
		FROM BODEGA_BIGGI.dbo.LOG_CAMBIO LC
			,BODEGA_BIGGI.dbo.DETALLE_CAMBIO DC
			,BODEGA_BIGGI.dbo.USUARIO U
		WHERE LC.COD_LOG_CAMBIO > @vl_cod_log_cambio
		AND LC.COD_LOG_CAMBIO = DC.COD_LOG_CAMBIO
		AND U.COD_USUARIO = LC.COD_USUARIO
		AND NOM_TABLA = 'PRODUCTO'
		AND NOM_CAMPO = 'PRECIO_VENTA_INTERNO'

		SELECT @vl_cod_log_cambio = CONVERT(NUMERIC, VALOR) 
		FROM PARAMETRO
		WHERE COD_PARAMETRO = '86'

		INSERT INTO DETALLE_PRODUCTO_CAMBIO
		SELECT LC.COD_LOG_CAMBIO
			 ,FECHA_CAMBIO
			 ,NOM_USUARIO
			 ,KEY_TABLA
			 ,VALOR_ANTIGUO
			 ,VALOR_NUEVO
			 ,'TODOINOX'
		FROM TODOINOX.dbo.LOG_CAMBIO LC
			,TODOINOX.dbo.DETALLE_CAMBIO DC
			,TODOINOX.dbo.USUARIO U
		WHERE LC.COD_LOG_CAMBIO > @vl_cod_log_cambio
		AND LC.COD_LOG_CAMBIO = DC.COD_LOG_CAMBIO
		AND U.COD_USUARIO = LC.COD_USUARIO
		AND NOM_TABLA = 'PRODUCTO'
		AND NOM_CAMPO = 'PRECIO_VENTA_INTERNO'

	END
	ELSE IF (@ve_operacion='UPDATE')BEGIN
		DECLARE	@vl_last_reg numeric(10)

		SELECT @vl_cod_log_cambio = CONVERT(NUMERIC, VALOR) 
		FROM PARAMETRO
		WHERE COD_PARAMETRO = '84'

		INSERT INTO DETALLE_PRODUCTO_CAMBIO
		SELECT LC.COD_LOG_CAMBIO
			 ,FECHA_CAMBIO
			 ,NOM_USUARIO
			 ,KEY_TABLA
			 ,VALOR_ANTIGUO
			 ,VALOR_NUEVO
			 ,'COMERCIAL'
		FROM LOG_CAMBIO LC
			,DETALLE_CAMBIO DC
			,USUARIO U
		WHERE LC.COD_LOG_CAMBIO > @vl_cod_log_cambio
		AND LC.COD_LOG_CAMBIO = DC.COD_LOG_CAMBIO
		AND U.COD_USUARIO = LC.COD_USUARIO
		AND NOM_TABLA = 'PRODUCTO'
		AND NOM_CAMPO = 'PRECIO_VENTA_INTERNO'

		SELECT @vl_cod_log_cambio = CONVERT(NUMERIC, VALOR) 
		FROM PARAMETRO
		WHERE COD_PARAMETRO = '85'

		INSERT INTO DETALLE_PRODUCTO_CAMBIO
		SELECT LC.COD_LOG_CAMBIO
			 ,FECHA_CAMBIO
			 ,NOM_USUARIO
			 ,KEY_TABLA
			 ,VALOR_ANTIGUO
			 ,VALOR_NUEVO
			 ,'BODEGA'
		FROM BODEGA_BIGGI.dbo.LOG_CAMBIO LC
			,BODEGA_BIGGI.dbo.DETALLE_CAMBIO DC
			,BODEGA_BIGGI.dbo.USUARIO U
		WHERE LC.COD_LOG_CAMBIO > @vl_cod_log_cambio
		AND LC.COD_LOG_CAMBIO = DC.COD_LOG_CAMBIO
		AND U.COD_USUARIO = LC.COD_USUARIO
		AND NOM_TABLA = 'PRODUCTO'
		AND NOM_CAMPO = 'PRECIO_VENTA_INTERNO'

		SELECT @vl_cod_log_cambio = CONVERT(NUMERIC, VALOR) 
		FROM PARAMETRO
		WHERE COD_PARAMETRO = '86'

		INSERT INTO DETALLE_PRODUCTO_CAMBIO
		SELECT LC.COD_LOG_CAMBIO
			 ,FECHA_CAMBIO
			 ,NOM_USUARIO
			 ,KEY_TABLA
			 ,VALOR_ANTIGUO
			 ,VALOR_NUEVO
			 ,'TODOINOX'
		FROM TODOINOX.dbo.LOG_CAMBIO LC
			,TODOINOX.dbo.DETALLE_CAMBIO DC
			,TODOINOX.dbo.USUARIO U
		WHERE LC.COD_LOG_CAMBIO > @vl_cod_log_cambio
		AND LC.COD_LOG_CAMBIO = DC.COD_LOG_CAMBIO
		AND U.COD_USUARIO = LC.COD_USUARIO
		AND NOM_TABLA = 'PRODUCTO'
		AND NOM_CAMPO = 'PRECIO_VENTA_INTERNO'

		SELECT @vl_last_reg = MAX(T_COD_LOG_CAMBIO)
		FROM DETALLE_PRODUCTO_CAMBIO
		WHERE T_ORIGEN = 'COMERCIAL'

		if(@vl_last_reg IS NOT NULL)BEGIN
			UPDATE PARAMETRO
			SET VALOR = @vl_last_reg
			WHERE COD_PARAMETRO = '84'
		END

		SELECT @vl_last_reg = MAX(T_COD_LOG_CAMBIO)
		FROM DETALLE_PRODUCTO_CAMBIO
		WHERE T_ORIGEN = 'BODEGA'

		if(@vl_last_reg IS NOT NULL)BEGIN
			UPDATE PARAMETRO
			SET VALOR = @vl_last_reg
			WHERE COD_PARAMETRO = '85'
		END

		SELECT @vl_last_reg = MAX(T_COD_LOG_CAMBIO)
		FROM DETALLE_PRODUCTO_CAMBIO
		WHERE T_ORIGEN = 'TODOINOX'

		if(@vl_last_reg IS NOT NULL)BEGIN
			UPDATE PARAMETRO
			SET VALOR = @vl_last_reg
			WHERE COD_PARAMETRO = '86'
		END
	END
END