ALTER PROCEDURE [dbo].[spi_tiene_bitacora]
AS
BEGIN
	declare @TEMPO TABLE    
	   (COD_USUARIO			numeric)
	
	-- Usuarios que tengan compromisos para hoy	
	INSERT INTO @TEMPO
	SELECT COD_USUARIO 
	FROM USUARIO 
	WHERE AUTORIZA_INGRESO = 'S'
	AND COD_USUARIO in (select CO.COD_USUARIO_VENDEDOR1
						from BITACORA_COTIZACION BI
							,COTIZACION CO
						where CO.COD_COTIZACION = BI.COD_COTIZACION
						and CO.COD_USUARIO_VENDEDOR1 not in (2, 4)	--AS, SP
						and CO.COD_ESTADO_COTIZACION not in (4, 5)	--concretada y rechazada
						and BI.FECHA_COMPROMISO <= DATEADD(SECOND,86400 - 1, DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
						AND BI.FECHA_COMPROMISO >= DATEADD(SECOND,0 , DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE()))))
						
	-- Usuarios que tengan compromisos para mañana	
	INSERT INTO @TEMPO
	SELECT COD_USUARIO 
	FROM USUARIO 
	WHERE AUTORIZA_INGRESO = 'S'
	AND COD_USUARIO in (select CO.COD_USUARIO_VENDEDOR1
						from BITACORA_COTIZACION BI
							,COTIZACION CO
						where BI.FECHA_COMPROMISO > DATEADD(SECOND,86400 - 1, DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
						and CO.COD_USUARIO_VENDEDOR1 not in (2, 4)
						and CO.COD_ESTADO_COTIZACION not in (4, 5)
						and CO.COD_COTIZACION = BI.COD_COTIZACION)
						
	-- Usuarios que tengan compromisos para ayer	
	INSERT INTO @TEMPO
	SELECT COD_USUARIO 
	FROM USUARIO 
	WHERE AUTORIZA_INGRESO = 'S'
	AND COD_USUARIO in (select CO.COD_USUARIO_VENDEDOR1
						from BITACORA_COTIZACION BI
							,COTIZACION CO
						where BI.FECHA_COMPROMISO < DATEADD(SECOND,0 , DBO.F_MAKEDATE(DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())))
						and CO.COD_USUARIO_VENDEDOR1 not in (2, 4)	--AS, SP
						and CO.COD_ESTADO_COTIZACION not in (4, 5)	--concretada y rechazada
						and CO.COD_COTIZACION = BI.COD_COTIZACION)				
	
	SELECT DISTINCT COD_USUARIO FROM @TEMPO
END