
CREATE TABLE [dbo].[CARTOLA_PARTICIPACION](
	[COD_CARTOLA_PARTICIPACION] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[COD_USUARIO] [numeric](10, 0) NOT NULL,
 CONSTRAINT [PK_CARTOLA_PARTICIPACION] PRIMARY KEY CLUSTERED 
(
	[COD_CARTOLA_PARTICIPACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 



CREATE TABLE [dbo].[ITEM_CARTOLA_PARTICIPACION](
	[COD_ITEM_CARTOLA_PARTICIPACION] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[COD_CARTOLA_PARTICIPACION] [numeric](10, 0) NOT NULL,
	[TIPO_MOVIMIENTO] [varchar](10) NOT NULL,
	[COD_PARTICIPACION] [numeric](10, 6) NULL,
	[FECHA_MOVIMIENTO] [date] NOT NULL,
	[GLOSA] [varchar](100) NOT NULL,
	[MONTO] [numeric](10, 0) NOT NULL,
	[COD_USUARIO] [numeric](10, 0) NOT NULL,
	[SALDO] [numeric](10, 0) NULL)